---
- name: Deploy Custom Nginx to K3d
  hosts: localhost
  connection: local
  tasks:
    - name: Create Nginx Deployment
      kubernetes.core.k8s:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: my-nginx-web
            namespace: default
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: web-custom
            template:
              metadata:
                labels:
                  app: web-custom
              spec:
                containers:
                - name: nginx
                  image: my-custom-nginx:latest
                  imagePullPolicy: Never
                  ports:
                  - containerPort: 80

    - name: Create Nginx Service
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: my-nginx-service
          spec:
            type: NodePort
            selector:
              app: web-custom
            ports:
            - port: 80
              nodePort: 30081
